spring:
  application:
    name: gateway
  cloud:
    gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
        routes:
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com
          filters:
          - RewritePath=/placeholder/,/
          predicates:
          - Path=/placeholder/todos/**

        - id: pokeapi
          uri: https://pokeapi.co
          predicates:
          - Path=/api/v2/**

        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
          - Path=/get


        
        